swiftmailer:
    #    url: '%env(MAILER_URL)%'
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

parameters:
    mailer_transport: smtp
    mailer_host: smtp.1and1.com
    mailer_por: 587
    mailer_user: contact@monsite.com
    mailer_password: mdp
    mailer_auth_mode: login
    sender_name: Nonsite